### ISSUE TITLE
v1.0.0 Checklist

### ISSUE THREAD

**Issue by HelloCore** [danger/dart#2]
Types
- [x] Git
- [x] Bitbucket Cloud
- [x] Github (https://github.com/danger/danger.dart/pull/4)

Misc
- [x] Documents (https://github.com/danger/danger.dart/pull/11)
- [x] More Tests (https://github.com/danger/danger.dart/pull/10)
- [x] Provide way to debug dangerfile (https://github.com/danger/danger.dart/pull/6)
- [x] Plugin (https://github.com/danger/danger.dart/pull/8)
- [x] API to get diff (https://github.com/danger/danger.dart/pull/34)
